version: '3'
services:
  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P1b7JBvP8II4
      MYSQL_DATABASE: webappdb
      MYSQL_USER: kojibello
      MYSQL_PASSWORD: P1b7JBvP8II4

  sonarqube:
    depends_on:
      - db
    image: kojibello/kojitechs-registration-app:1.2.01-pre-release
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_NAME: webappdb
      DB_USERNAME: kojibello
      DB_PASSWORD: P1b7JBvP8II4
volumes:
  mysql-data: